 - name: "My setup for fedora 37"
   hosts: localhost
   connection: localhost
   become: true
   vars:
     user: pdahse
     font: "Hack Nerd Font Mono Regular" # todo currently installed in oh-my-zsh role -> should be separated
   roles:
     - { role: pkgs-dnf, tags: ['dnf'] }
     - { role: pkgs-flatpak, tags: ['flatpak'] }
     - { role: pkgs-pip, tags: ['pip'] }
     - { role: cisco-anyconnect-vpn-client, tags: ['anyconnect'] }
     - { role: terminator, tags: ['terminator'] }
     - { role: oh-my-zsh, tags: ['omz'] }
     - { role: virtualbox, tags: ['vbox'] }
     - { role: vagrant, tags: ['vagrant'] }
     - { role: nvm, tags: ['nvm'] }
     - { role: git-flow-avh, tags: ['git-flow'] }
     - { role: git-commit-flow, tags: ['git-commit-flow'] }
#     - { role: insomnia, tags: ['insomnia'] } # todo pdahse not working corrently with ansible / manually works
