- name: # install fibers system dependencies
  dnf:
    name: '@Development tools'
    state: present

- block: # todo pdahse last time this was not installed because the dot files where copied before
  - name: Check if nvm is loaded
    lineinfile:
      line: 'export NVM_DIR="$HOME/.nvm"'
      path: "{{ lookup('env', 'HOME') }}/.zshrc"
    check_mode: true
    register: nvm_loaded

  - name: Install install nvm
    shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    when: nvm_loaded.changed

  - name: Install yarn
    npm:
      name: yarn
      global: yes
  become_user: pdahse

# todo
# also this part needed to be moved to the top manuelly
# -------------------------------------
#  export NVM_DIR="$HOME/.nvm"
#  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
