- name: install fibers system dependencies
  dnf:
    name: '@Development tools'
    state: present

- block:
  - name: Check if nvm is loaded
    lineinfile:
      line: 'export NVM_DIR="$HOME/.nvm"'
      path: "{{ lookup('env', 'HOME') }}/.zshrc"
    check_mode: true
    register: nvm_loaded

  - name: Download nvm installer
    get_url:
      url: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh"
      dest: /tmp/nvm-install.sh
      mode: 0755
    when: nvm_loaded.changed

  - name: Run nvm installer
    shell: /tmp/nvm-install.sh
    args:
      executable: /bin/bash
    when: nvm_loaded.changed

  become_user: pdahse

# todo
# also this part needed to be moved to the top manuelly
# -------------------------------------
#  export NVM_DIR="$HOME/.nvm"
#  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
