- name: Add unetbootin repo
  apt_repository:
    repo: 'ppa:gezakovacs/ppa'
    state: present

- name: Install unetbootin
  apt:
    pkg:
      - unetbootin
    state: present
    update_cache: true