- block:
    - name: Ensure fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: Copy all fonts
      copy:
        src: '{{ item }}'
        dest: "{{ lookup('env', 'HOME') }}/.fonts"
      with_fileglob: "files/*.ttf"
      register: fonts

    - name: Rebuild fonts cache
      shell: fc-cache -f -v
      when: fonts.changed

    - name: Register var on oh-my-zsh path
      stat:
        path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
      register: oh_my_zsh_dir

    - name: Install oh-my-zsh if isn't already
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: oh_my_zsh_dir.stat.exists == false

    - name: Register var on powerlevel10k path
      stat:
        path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
      register: powerlevel10k

    - name: Install powerlevel10k if isn't already
      git:
        repo: 'https://github.com/romkatv/powerlevel10k.git'
        dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1
      when: powerlevel10k.stat.exists == false

    - name: Set powerlevel10k as theme in zshrc
      lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.zshrc"
        regexp: '^ZSH_THEME='
        line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
      when: powerlevel10k.stat.exists == false

    - name: Copy p10k config into home directory
      copy:
        src: 'files/.p10k.zsh'
        dest: "{{ lookup('env', 'HOME') }}/.p10k.zsh"
      when: powerlevel10k.stat.exists == false

    - name: Enable Powerlevel10k instant prompt
      lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.zshrc"
        insertbefore: BOF
        line: |
          # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
          # Initialization code that may require console input (password prompts, [y/n]
          # confirmations, etc.) must go above this block; everything else may go below.
          if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
            source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
          fi
      when: powerlevel10k.stat.exists == false

    - name: Load Powerlevel10k prompt config
      lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.zshrc"
        insertafter: EOF
        line: |
          # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
          [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
      when: powerlevel10k.stat.exists == false

    - name: copy .zsh_aliases to home
      copy:
        src: 'files/.zsh_aliases'
        dest: "{{ lookup('env', 'HOME') }}/.zsh_aliases"

    - name: Check if .zsh_aliases is sourced in .zshrc
      lineinfile:
        line: '[[ ! -f ~/.zsh_aliases ]] || source ~/.zsh_aliases'
        path: "{{ lookup('env', 'HOME') }}/.zshrc"
      check_mode: true
      register: zsh_aliases_sourced

    - name: Source zsh_aliases
      lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.zshrc"
        insertafter: EOF
        line: '[[ ! -f ~/.zsh_aliases ]] || source ~/.zsh_aliases'
      when: zsh_aliases_sourced.changed
  become_user: pdahse
