- name: Install terminator
  dnf:
    name: terminator
    state: present

- name: Ensure termintor config directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/terminator"
    state: directory
  become_user: pdahse

- name: Copy terminator config
  template:
    src: templates/config
    dest: "{{ lookup('env', 'HOME') }}/.config/terminator/config"
  become_user: pdahse