- shell: uname -r
  register: uname_r

- name: Install virtual box dependencies
  dnf:
    name:
      - gcc
      - binutils
      - make
      - glibc-devel
      - patch
      - libgomp
      - glibc-headers
      - kernel-headers
      - "kernel-devel-{{ uname_r.stdout }}"
      - dkms
    state: present

- name: Install virtualbox
  dnf:
    name:
     - VirtualBox
     - akmod-VirtualBox
     - VirtualBox-guest-additions
    state: present

- name: Adding the user to vboxusers group
  user:
    name: pdahse # todo use a variable here
    groups: vboxusers
    append: yes
