- name: Add the flathub flatpak repository remote to the user installation
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install all packages where only flatpak install in needed
  flatpak:
    name: "{{ item }}"
    state: present
  with_items:
    - org.keepassxc.KeePassXC                 # old school Password manager for work
    - com.jetbrains.PhpStorm                  # IDE
    - org.signal.Signal                       # Messenger
    - com.slack.Slack                         # Chat
    - md.obsidian.Obsidian                    # Markdown Notes Tool
    - rest.insomnia.Insomnia                  # Tool to make and analyse requests
