# https://www.linuxbuzz.com/install-docker-on-fedora-step-by-step/
- name: check if docker repository exists
  stat:
    path: /etc/yum.repos.d/docker.repo
  register: docker_repo_file

- name: download docker repository
  get_url:
    url: "https://download.docker.com/linux/fedora/docker-ce.repo"
    dest: /etc/yum.repos.d/docker.repo
  when: docker_repo_file.stat.exists == False

- name: Install docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Enable service docker
  systemd:
    name: docker
    enabled: yes