- name: Add PHP
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present

- name: Update cache
  apt:
    update_cache: true

- name: Install php7.4
  apt:
    pkg:
      - "{{ item }}"
    state: present
  with_items:
    - php7.4
    - php-common
    - php-mongodb
    - php7.4-bcmath
    - php7.4-bz2
    - php7.4-cli
    - php7.4-common
    - php7.4-curl
    - php7.4-dev
    - php7.4-gd
    - php7.4-imap
    - php7.4-intl
    - php7.4-json
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-opcache
    - php7.4-mcrypt
    - php7.4-readline
    - php7.4-xml
    - php7.4-zip

- name: Install php8.1
  apt:
    pkg:
      - "{{ item }}"
    state: present
  with_items:
    - php8.1
    - php-common
    - php-mongodb
    - php8.1-bcmath
    - php8.1-bz2
    - php8.1-cli
    - php8.1-common
    - php8.1-curl
    - php8.1-dev
    - php8.1-gd
    - php8.1-imap
    - php8.1-intl
    - php8.1-json
    - php8.1-mbstring
    - php8.1-mysql
    - php8.1-opcache
    - php8.1-mcrypt
    - php8.1-readline
    - php8.1-xml
    - php8.1-zip

- name: Switch php version
  shell: "{{ item }}"
  with_items:
    - "update-alternatives --set php /usr/bin/php{{ php_version }}"
    - "update-alternatives --set phar /usr/bin/phar{{ php_version }}"
    - "update-alternatives --set phar.phar /usr/bin/phar.phar{{ php_version }}"
  tags: ['php-version']