 - name: "My setup for Fedora"
   hosts: localhost
   connection: localhost
   become: true

   vars:
     font: "Hack Nerd Font Mono Regular"
     user: pdahse

   roles:
     - { role: ../roles/pkgs-dnf, tags: ['dnf'] }
     - { role: ../roles/pkgs-flatpak, tags: ['flatpak'] }
     - { role: ../roles/pkgs-pip, tags: ['pip'] }
     - { role: ../roles/fonts, tags: ['fonts'] }
     - { role: ../roles/cisco-anyconnect-vpn-client, tags: ['anyconnect'] }
     - { role: ../roles/terminator, tags: ['terminator'] }
     - { role: ../roles/oh-my-zsh, tags: ['omz'] }
     - { role: ../roles/firewall, tags: ['firewall'] }
#     - { role: ../roles/virtualbox, tags: ['vbox'] } # problems with latest version (7.0.4) installed 6.1 manually
     - { role: ../roles/vagrant, tags: ['vagrant'] }
     - { role: ../roles/nodejs, tags: ['nodejs'] }
     - { role: ../roles/git-flow-avh, tags: ['git-flow'] }
     - { role: ../roles/git-commit-flow, tags: ['git-commit-flow'] }
     - { role: ../roles/touchegg, tags: ['touchegg'] }
     - { role: ../roles/docker, tags: ['docker'] }
     - { role: ../roles/pdfsam, tags: ['pdfsam'] }
     - { role: ../roles/hetzner-cloud, tags: ['hcloud'] }
